name: Auto Commit Contribution

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:


permissions:
  contents: write


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


jobs:

  update:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0


      - name: Update activity
        run: |

          echo "# Daily Update" > activity.md

          echo "Updated: $(date)" >> activity.md


      - name: Commit
        run: |

          git config user.name "nasrul12-sudo"

          git config user.email "maznanas59@gmail.com"


          git add .

          git commit -m "chore: daily update" || exit 0

          git push